/* prettier-ignore-start */
/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file is auto-generated by TanStack Router
import { createFileRoute } from '@tanstack/react-router';
// Import Routes
import { Route as rootRoute } from './routes/__root';
import { Route as IndexImport } from './routes/index';
import { Route as WorkflowsIndexImport } from './routes/workflows/index';
import { Route as WorkflowsEditorImport } from './routes/workflows/editor';
// Create Virtual Routes
const WorkflowsImport = createFileRoute('/workflows')();
// Create/Update Routes
const WorkflowsRoute = WorkflowsImport.update({
    path: '/workflows',
    getParentRoute: () => rootRoute,
});
const IndexRoute = IndexImport.update({
    path: '/',
    getParentRoute: () => rootRoute,
});
const WorkflowsIndexRoute = WorkflowsIndexImport.update({
    path: '/',
    getParentRoute: () => WorkflowsRoute,
});
const WorkflowsEditorRoute = WorkflowsEditorImport.update({
    path: '/editor',
    getParentRoute: () => WorkflowsRoute,
});
// Create and export the route tree
export const routeTree = rootRoute.addChildren([
    IndexRoute,
    WorkflowsRoute.addChildren([WorkflowsEditorRoute, WorkflowsIndexRoute]),
]);
/* prettier-ignore-end */
