/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as WorkflowsIndexImport } from './routes/workflows/index'
import { Route as WorkflowsEditorImport } from './routes/workflows/editor'

// Create Virtual Routes

const WorkflowsImport = createFileRoute('/workflows')()

// Create/Update Routes

const WorkflowsRoute = WorkflowsImport.update({
    path: '/workflows',
    getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
    path: '/',
    getParentRoute: () => rootRoute,
} as any)

const WorkflowsIndexRoute = WorkflowsIndexImport.update({
    path: '/',
    getParentRoute: () => WorkflowsRoute,
} as any)

const WorkflowsEditorRoute = WorkflowsEditorImport.update({
    path: '/editor',
    getParentRoute: () => WorkflowsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            preLoaderRoute: typeof IndexImport
            parentRoute: typeof rootRoute
        }
        '/workflows': {
            preLoaderRoute: typeof WorkflowsImport
            parentRoute: typeof rootRoute
        }
        '/workflows/editor': {
            preLoaderRoute: typeof WorkflowsEditorImport
            parentRoute: typeof WorkflowsImport
        }
        '/workflows/': {
            preLoaderRoute: typeof WorkflowsIndexImport
            parentRoute: typeof WorkflowsImport
        }
    }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
    IndexRoute,
    WorkflowsRoute.addChildren([WorkflowsEditorRoute, WorkflowsIndexRoute]),
])

/* prettier-ignore-end */
