import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useState } from 'react';
import { X } from 'lucide-react';
import { useWorkflowStore } from '@/stores/workflowStore';
export function NodeConfigPanel() {
    const { selectedNode, updateNodeData } = useWorkflowStore();
    const [config, setConfig] = useState(selectedNode?.data.config || {});
    if (!selectedNode) {
        return (_jsx("div", { className: "w-80 border-l border-gray-200 bg-gray-50 p-6 flex items-center justify-center", children: _jsx("p", { className: "text-gray-400 text-sm text-center", children: "\u70B9\u51FB\u8282\u70B9\u4EE5\u914D\u7F6E\u5C5E\u6027" }) }));
    }
    const handleSave = () => {
        updateNodeData(selectedNode.id, { config });
    };
    return (_jsxs("div", { className: "w-80 border-l border-gray-200 bg-gray-50 overflow-y-auto", children: [_jsxs("div", { className: "p-4 border-b border-gray-200 bg-white", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("h3", { className: "text-lg font-bold text-gray-800", children: "\u8282\u70B9\u914D\u7F6E" }), _jsx("button", { onClick: () => useWorkflowStore.getState().selectNode(null), className: "p-1 hover:bg-gray-100 rounded", children: _jsx(X, { className: "w-5 h-5 text-gray-500" }) })] }), _jsx("p", { className: "text-sm text-gray-500 mt-1", children: selectedNode.data.label })] }), _jsxs("div", { className: "p-4 space-y-4", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "\u8282\u70B9\u540D\u79F0" }), _jsx("input", { type: "text", value: selectedNode.data.label, onChange: (e) => updateNodeData(selectedNode.id, { label: e.target.value }), className: "w-full px-3 py-2 border border-gray-300 rounded-md focus:ring-2 focus:ring-blue-500 focus:border-transparent" })] }), selectedNode.type === 'trigger' && (_jsx(TriggerConfig, { config: config, setConfig: setConfig })), selectedNode.type === 'condition' && (_jsx(ConditionConfig, { config: config, setConfig: setConfig })), selectedNode.type === 'action' && (_jsx(ActionConfig, { config: config, setConfig: setConfig })), _jsx("button", { onClick: handleSave, className: "w-full bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 transition-colors", children: "\u4FDD\u5B58\u914D\u7F6E" })] })] }));
}
// 触发器配置
function TriggerConfig({ config, setConfig }) {
    return (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "\u6D88\u606F\u6765\u6E90" }), _jsxs("select", { value: config.source || 'current', onChange: (e) => setConfig({ ...config, source: e.target.value }), className: "w-full px-3 py-2 border border-gray-300 rounded-md", children: [_jsx("option", { value: "current", children: "\u5F53\u524D\u8D26\u53F7" }), _jsx("option", { value: "all", children: "\u6240\u6709\u8D26\u53F7" })] })] }));
}
// 条件配置
function ConditionConfig({ config, setConfig }) {
    return (_jsxs(_Fragment, { children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "\u5339\u914D\u7C7B\u578B" }), _jsxs("select", { value: config.matchType || 'exact', onChange: (e) => setConfig({ ...config, matchType: e.target.value }), className: "w-full px-3 py-2 border border-gray-300 rounded-md", children: [_jsx("option", { value: "exact", children: "\u7CBE\u786E\u5339\u914D" }), _jsx("option", { value: "regex", children: "\u6B63\u5219\u8868\u8FBE\u5F0F" }), _jsx("option", { value: "semantic", children: "\u8BED\u4E49\u5339\u914D" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: config.matchType === 'semantic' ? '语义意图' : '匹配模式' }), _jsx("input", { type: "text", value: config.pattern || '', onChange: (e) => setConfig({ ...config, pattern: e.target.value }), placeholder: config.matchType === 'semantic' ? '例如：问候语' : '例如：你好', className: "w-full px-3 py-2 border border-gray-300 rounded-md" })] })] }));
}
// 动作配置
function ActionConfig({ config, setConfig }) {
    return (_jsxs(_Fragment, { children: [_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "\u52A8\u4F5C\u7C7B\u578B" }), _jsxs("select", { value: config.actionType || 'send_message', onChange: (e) => setConfig({ ...config, actionType: e.target.value }), className: "w-full px-3 py-2 border border-gray-300 rounded-md", children: [_jsx("option", { value: "send_message", children: "\u53D1\u9001\u6D88\u606F" }), _jsx("option", { value: "click", children: "\u70B9\u51FB\u5143\u7D20" }), _jsx("option", { value: "input", children: "\u8F93\u5165\u6587\u672C" }), _jsx("option", { value: "wait", children: "\u7B49\u5F85" })] })] }), config.actionType === 'send_message' && (_jsxs("div", { children: [_jsx("label", { className: "block text-sm font-medium text-gray-700 mb-1", children: "\u6D88\u606F\u5185\u5BB9" }), _jsx("textarea", { value: config.message || '', onChange: (e) => setConfig({ ...config, message: e.target.value }), rows: 3, className: "w-full px-3 py-2 border border-gray-300 rounded-md" })] })), _jsxs("div", { className: "p-3 bg-purple-50 rounded-md border border-purple-200", children: [_jsx("h4", { className: "text-sm font-semibold text-purple-900 mb-2", children: "\u62DF\u4EBA\u5316\u53C2\u6570" }), _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { children: [_jsx("label", { className: "block text-xs text-purple-700 mb-1", children: "\u5EF6\u8FDF\u8303\u56F4 (ms)" }), _jsxs("div", { className: "flex gap-2", children: [_jsx("input", { type: "number", placeholder: "\u6700\u5C0F", value: config.delayMin || 1000, onChange: (e) => setConfig({ ...config, delayMin: parseInt(e.target.value) }), className: "w-1/2 px-2 py-1 text-sm border border-purple-300 rounded" }), _jsx("input", { type: "number", placeholder: "\u6700\u5927", value: config.delayMax || 3000, onChange: (e) => setConfig({ ...config, delayMax: parseInt(e.target.value) }), className: "w-1/2 px-2 py-1 text-sm border border-purple-300 rounded" })] })] }), _jsxs("div", { children: [_jsx("label", { className: "block text-xs text-purple-700 mb-1", children: "\u9519\u8BEF\u7387" }), _jsx("input", { type: "range", min: "0", max: "100", value: (config.errorRate || 0) * 100, onChange: (e) => setConfig({ ...config, errorRate: parseInt(e.target.value) / 100 }), className: "w-full" }), _jsxs("span", { className: "text-xs text-purple-600", children: [((config.errorRate || 0) * 100).toFixed(0), "%"] })] })] })] })] }));
}
